name: Render Rmd

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Restore renv cache
      uses: actions/cache@v2
      with:
        path: renv/cache
        key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
        restore-keys: |
          ${{ runner.os }}-renv-

    - name: Install dependencies with renv
      run: |
        Rscript -e 'renv::restore()'

    - name: Render Rmd file
      run: |
        Rscript -e 'rmarkdown::render("analyze_stats.Rmd")'

    - name: Upload rendered HTML
      uses: actions/upload-pages-artifact@v4
      with:
        path: .

  publish:
    needs: render

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

  # Specify runner + deployment step
  runs-on: ubuntu-latest
  steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4 
